# -*- coding: utf-8 -*-
"""Market Basket Analyst - New Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2ZRK6dmplwyIdILCSZ0q3bmv8oYo7cu
"""

# Import library yang dibutuhkan
!pip install streamlit

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
import networkx as nx
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error
import streamlit as st
from datetime import datetime

df = pd.read_csv('online_retail.csv')
df.head()

df.info()

df.shape

# 2. Preprocessing
# Ubah InvoiceDate ke datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Cek missing value dan duplikat
print("Missing Values:\n", df.isnull().sum())
print("Duplicated Rows:", df.duplicated().sum())

# Drop missing CustomerID dan Description
df = df.dropna(subset=['CustomerID', 'Description'])
df = df.drop_duplicates()

df.shape

# Cek missing value dan duplikat
print("Missing Values:\n", df.isnull().sum())
print("Duplicated Rows:", df.duplicated().sum())

# Filter transaksi valid (Quantity > 0, UnitPrice > 0)
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

# Tambah kolom TotalPrice
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

# Cek anomali: InvoiceNo yang dimulai dengan 'C' (cancelled)
df = df[~df['InvoiceNo'].str.startswith('C')]

# Cek data setelah preprocessing
print("Data Shape setelah Preprocessing:", df.shape)
print(df.info())

# 3. Market Basket Analysis
# Filter data UK (fokus ke pasar terbesar)
df_uk = df[df['Country'] == 'United Kingdom']

# Buat basket: pivot table berdasarkan InvoiceNo dan Description
basket = df_uk.groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().fillna(0)
basket = basket.applymap(lambda x: 1 if x > 0 else 0)

top_10_products = df_uk['Description'].value_counts().head(10)

plt.figure(figsize=(10,6))
top_10_products.plot(kind='bar')
plt.title('Top 10 Produk Terbanyak dalam Transaksi')
plt.xlabel('Produk')
plt.ylabel('Jumlah Transaksi')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y')
plt.show()

# Apriori: Eksperimen dengan min_support=0.02
frequent_itemsets = apriori(basket, min_support=0.02, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
print("\nFrequent Itemsets:\n", frequent_itemsets.head(10))

# Association Rules: min_confidence=0.6
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
rules = rules[rules['lift'] > 1.2]
print("\nTop Association Rules:\n", rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head())

# Visualisasi: Network Graph untuk Rules
G = nx.DiGraph()
for idx, rule in rules.head(5).iterrows():
    for ant in rule['antecedents']:
        for cons in rule['consequents']:
            G.add_edge(ant, cons, weight=rule['lift'])
plt.figure(figsize=(10,8))
pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=2000, font_size=8)
nx.draw_networkx_edge_labels(G, pos, edge_labels={(u,v): f"Lift: {d['weight']:.2f}" for u,v,d in G.edges(data=True)})
plt.title('Network of Top Product Associations')
plt.show()

# Visualisasi: Barplot Top 5 Rules
top_rules = rules.nlargest(5, 'lift')
plt.figure(figsize=(10,6))
sns.barplot(x='lift', y=top_rules['consequents'].apply(lambda x: ', '.join(x)), hue='confidence', data=top_rules)
plt.title('Top 5 Association Rules by Lift')
plt.xlabel('Lift')
plt.ylabel('Consequents')
plt.show()

# Rekomendasi untuk produk spesifik
focus_item = 'GREEN REGENCY TEACUP AND SAUCER'
rekomendasi = rules[rules['antecedents'].apply(lambda x: focus_item in x if isinstance(x, frozenset) else False)]
print(f"\nRekomendasi jika beli {focus_item}:\n", rekomendasi[['consequents', 'confidence', 'lift']])

# 4. Time Series Analysis
# Agregasi harian untuk jumlah transaksi
daily_trx = df.groupby(df['InvoiceDate'].dt.date)['InvoiceNo'].nunique().reset_index()
daily_trx.columns = ['Date', 'Transaction_Count']
daily_trx['Date'] = pd.to_datetime(daily_trx['Date'])

# Cek stationarity
adf_result = adfuller(daily_trx['Transaction_Count'])
print("\nADF Test p-value:", adf_result[1])
if adf_result[1] > 0.05:
    daily_trx['Transaction_Count_Diff'] = daily_trx['Transaction_Count'].diff().dropna()
    adf_diff = adfuller(daily_trx['Transaction_Count_Diff'].dropna())
    print("ADF Test p-value after differencing:", adf_diff[1])

# Split train-test
train_data = daily_trx['Transaction_Count'][:-30]
test_data = daily_trx['Transaction_Count'][-30:]

# Print shape data train dan test
print("Shape Data Train:", train_data.shape)
print("Shape Data Test:", test_data.shape)

# Model ARIMA
arima_model = ARIMA(train_data, order=(1,1,1)).fit()
arima_pred = arima_model.forecast(steps=30)

# Evaluasi model
mae = mean_absolute_error(test_data, arima_pred)
print("MAE:", mae)

# Visualisasi: Prediksi vs Aktual
plt.figure(figsize=(12,6))
plt.plot(daily_trx['Date'][-30:], test_data, label='Actual', marker='o')
plt.plot(daily_trx['Date'][-30:], arima_pred, label='Predicted', marker='x')
plt.title('Prediksi vs Aktual Jumlah Transaksi Harian')
plt.xlabel('Tanggal')
plt.ylabel('Jumlah Transaksi')
plt.legend()
plt.grid()
plt.show()

# Visualisasi: Tren Musiman (Bulanan)
monthly_trx = df.groupby(df['InvoiceDate'].dt.to_period('M'))['InvoiceNo'].nunique().reset_index()
monthly_trx['InvoiceDate'] = monthly_trx['InvoiceDate'].dt.to_timestamp()
plt.figure(figsize=(12,6))
plt.plot(monthly_trx['InvoiceDate'], monthly_trx['InvoiceNo'], marker='o', color='blue')
plt.title('Tren Jumlah Transaksi per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Transaksi')
plt.grid()
plt.show()

# 6. Simpan data untuk analisis lanjutan
df.to_csv('online_retail_cleaned.csv', index=False)